### ISSUE TITLE
fine-tunable?

### ISSUE THREAD

**Issue by jrobbl** [joeweiss/birdnetlib#121]
I read in kaggle models specification (https://www.kaggle.com/models/shadiakiki1/birdnetlib) that this is a fine-tunable model
Can you please provide an example on how to do this?
Thanks

**Comment by joeweiss** [comment]
Hi!

I'm not sure where kaggle's **fine-tunable** attribute is coming from, but that applies to the larger [BirdNET](https://github.com/kahst/BirdNET-Analyzer) project. `birdnetlib` is just one of the libraries that utilizes the models. 

You can find information on [training the models here](https://github.com/kahst/BirdNET-Analyzer?tab=readme-ov-file#8-training) at the BirdNET project's repo.
