### ISSUE TITLE
Repo fails to clone on Windows due to invalid filename paths in test files

### ISSUE THREAD

**Issue by LimitlessGreen** [joeweiss/birdnetlib#45]
Thank you for this great project :)
Sadly, I can't clone this repo under Windows, because Windows does not allow colons in file names.

```
error: invalid path 'tests/test_files/2022-08-15-birdnet-21:05:51.wav'
```

**Comment by joeweiss** [comment]
Thanks @LimitlessGreen. Pull request incoming.

**Comment by joeweiss** [comment]
Note: This fix does not necessitate a new version on `pip`. The issue only affects cloning the repo itself.
