### ISSUE TITLE
Rename to birdnet

### ISSUE THREAD

**Issue by Bengt** [joeweiss/birdnetlib#59]
The most obvious name is still available on PyPI:

https://pypi.org/search/?q=birdnet

**Comment by joeweiss** [comment]
Hi @Bengt, I appreciate the suggestion. I'm unsure if the BirdNET team is planning anything for `birdnet` on PyPI.

This library isn't an official component of the larger BirdNET project, so I feel uncomfortable taking the `birdnet` namespace.
