### ISSUE TITLE
Overlap parameter

### ISSUE THREAD

**Issue by gls21** [joeweiss/birdnetlib#68]
I'd like to be able to change the BirdNET overlap parameter in addition to changing parameters like min_conf. I am using the DirectoryAnalyzer class defined in batch.py but overlap doesn't appear as an option? Is there a way of doing this and can you provide an example please? 
Thanks!

**Comment by joeweiss** [comment]
Hi @gls21.

Thanks for pointing out this omission.

`overlap` isn't currently implemented, but it should be a simple addition, as that property is already included in the [Recording object] (https://github.com/joeweiss/birdnetlib/blob/e26bc1dae7ae1b08f9866ac75b152a6749c20686/src/birdnetlib/main.py#L37)and utilized by the two analyzer classes.

I'll add this to the todo list and see if I can get it out with the next release. My plan is to get a release out early next week assuming #66 is resolved by PyPi.

**Todo:**

- [ ] Add the overlap property to Analyzer init
- [ ] Add the overlap property to Lite-Analyzer init
- [ ] Update tests
- [ ] Update DirectoryAnalyzer
- [ ] Update DirectoryMultiProcessingAnalyzer
- [ ] Document
- [ ] Release

**Comment by joeweiss** [comment]
Starting with version 0.8, `overlap` can be passed `DirectoryAnalyzer`, `DirectoryMultiProcessingAnalyzer` or directly to the `Recording` class. The default for `overlap` is 0.0.

Example using DirectoryAnalyzer:
```
from birdnetlib.batch import DirectoryAnalyzer
from birdnetlib.analyzer import Analyzer
from datetime import datetime
from pprint import pprint


def on_analyze_complete(recording):
    print(recording.path)
    pprint(recording.detections)


def on_error(recording, error):
    print("An exception occurred: {}".format(error))
    print(recording.path)


print("Starting Analyzer")
analyzer = Analyzer()


print("Starting Watcher")
directory = "."
batch = DirectoryAnalyzer(
    directory,
    analyzers=[analyzer],
    lon=-120.7463,
    lat=35.4244,
    date=datetime(year=2022, month=5, day=10),
    min_conf=0.4,
    overlap=1.0,
)

batch.on_analyze_complete = on_analyze_complete
batch.on_error = on_error
batch.process()
```

Note: `overlap` is the equivalent of the `--overlap` parameter in the BirdNET's [command line tool](https://github.com/kahst/BirdNET-Analyzer#41-usage-cli).

```
--overlap, Overlap of prediction segments. Values in [0.0, 2.9]. Defaults to 0.0.
```
