### ISSUE TITLE
Relicense as CC-NC-BY-SA 4.0

### ISSUE THREAD

**Issue by Bengt** [joeweiss/birdnetlib#72]
I would like to merge this repository with the main BirdNET repository for easier maintenance of both parts. However, the GPL v3 license does not allow that without relicensing BirdNET-Analyzer under GPL v3, too. Therefore, please relicense this code under the term of the  [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

**Comment by joeweiss** [comment]
Hi @Bengt.

The CC BY-NC-SA 4.0 license is not an appropriate choice in my opinion, as the CC BY-NC-SA 4.0 license is not recommended for software by the authors of CC BY-NC-SA 4.0 here:
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

`birdnetlib` is a community-based project without a formal connection to the larger BirdNET project. My choice is to keep the Python code, Docker configs and CI/CD integrations that I develop and maintain as GPLv3, as the GPLv3 is an open source software license.

If you're a member of the BirdNET team and would like to propose a different organizational structure for community-based software repos, please reach out over email. Thanks.

**Comment by Bengt** [comment]
Hi @joeweiss,

thanks for clarifying. This statement is exactly what I was hoping for.

I agree that CC BY-NC-SA 4.0 is not an appropriate choice for a software package, but I disagree that GPLv3 is an appropriate choice for a software library.

I am not a member of the BirdNET team, but I would like to include your solutions into my fork, but due to the conflicting licenses, I cannot.

I have pinged the BirdNET team here: <https://github.com/kahst/BirdNET-Analyzer/issues/154>

**Comment by joeweiss** [comment]
> but I disagree that GPLv3 is an appropriate choice for a software library in particular.

@Bengt, I see your point. I'm a proponent of copyleft licenses, but perhaps the choice of software license should be revisited for `birdnetlib`. Of the more permissive licenses, I prefer Apache 2.0. 

I'll open a new issue.

Again, to be clear, I can only speak for myself and `birdnetlib`. 

I have no involvement with @Bengt's merged project, or the request to relicense BirdNET-Analyzer.
